### ISSUE TITLE
OpenVINO support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#191]
- [x] 1. Opening `rm_lstm4f.xml` results in TypeError (#192)
- [x] 2. dot files are not opened any more - need to fix it (#192)
- [x] 3. add preflight check for invalid xml and dot content
- [x] 6. Add test files to `./test/models.json` (#195) (#211)
- [x] 9. Add support for the version 3 of IR (#196)
- [x] 10. Category color support (#203)
- [x] 11. `-metadata.json` for coloring, documentation and attribute default filtering (#203).
- [x] 5. Filter attribute defaults based on `-metadata.json` to show fewer attributes in the graph
- [ ] 7. Show weight tensors
- [x] 8. Graph inputs and outputs should be exposed as Graph.inputs and Graph.outputs
- [x] 12. Move to `DOMParser`
- [x] 13. Remove `dot` support

**Comment by demid5111** [comment]
Also leftovers from the PR 189:

- Put OpenVINO XML/DOT parser generation logic in the ./tools directory.
- Add support for the -metadata.json file for better filtering of properties, group coloring etc.

**Comment by lutzroeder** [comment]
* Add `.dot` test files to `./test/models.json`

**Comment by lutzroeder** [comment]
Opening `rm_lstm4f.xml` results in `TypeError: Cannot read property 'output' of undefined`.

**Comment by lutzroeder** [comment]
* Graph inputs and outputs should be exposed as `Graph.inputs` and `Graph.outpus`

**Comment by demid5111** [comment]
- Add support for the version 3 of IR

**Comment by demid5111** [comment]
- dot files are not opened any more - need to fix it

**Comment by demid5111** [comment]
- add preflight check for the content, so that xml and dot files that are not IR will not be opened by the openvino.ModelFactory

**Comment by demid5111** [comment]
@lutzroeder I enumerated the list of issues to quickly reference in the PRs and also for discussions (status for the ww47.6):

1. Category color support
2. Filter attribute defaults to show fewer attributes in the graph
3. Show weight tensors
4. Put OpenVINO XML/DOT parser generation logic in the ./tools directory
5. Add support for the `-metadata.json` file for better filtering of properties, group coloring etc.
6. Add .dot test files to ./test/models.json
7. Opening `rm_lstm4f.xml` results in `TypeError: Cannot read property 'output' of undefined`. (#192)
8. Graph inputs and outputs should be exposed as `Graph.inputs` and `Graph.outpus`
9. Add support for the version 3 of IR
10. dot files are not opened any more - need to fix it (#192)
11. add preflight check for the content, so that xml and dot files that are not IR will not be opened by the openvino.ModelFactory (#192)

**Comment by demid5111** [comment]
@lutzroeder About item $6. There are two questions:

- I have an error running tests as I wrote in the first PR. I assume that this is due to different node versions because I have met similar problems each time when migrating (4->6, 6->7, 7->8, 8->10) . I am using node v10.13.0 (which is now LTS and stable). Are you using different node version? 
- dot files are not publicly available. Users generate dot files on their own when running the calibration tool inside the OpenVINO. where can I put sample files so that we can enable tests on them.
- is it possible to add negative cases? I mean files with errors: not correct structure, for example

**Comment by demid5111** [comment]
@lutzroeder About item $4. The parsers are generated with the `peg.js` library from the given `.peg` file. It is a grammar file and it is widely used as a technology for writing parsers of arbitrary files in JS. they are performant. What can I use as a reference of how to add the step of parser generation in Netron?

**Comment by lutzroeder** [comment]
> * I have an error running tests as I wrote in the first PR. I assume that this is due to different node versions because I have met similar problems each time when migrating (4->6, 6->7, 7->8, 8->10) . I am using node v10.13.0 (which is now LTS and stable). Are you using different node version?

I'm running `node v10.11.0` on `origin/master`. Which error are you seeing?

> dot files are not publicly available. Users generate dot files on their own when running the calibration tool inside the OpenVINO. where can I put sample files so that we can enable tests on them.

You can zip a small file, attach it to this GitHub issue and reference from there. Look for other zip references in `models.json` how to unzip via `[]` during download.

> is it possible to add negative cases? I mean files with errors: not correct structure, for example

Add an `error:` property with the expected error message.

> The parsers are generated with the peg.js library from the given .peg file. It is a grammar file and it is widely used as a technology for writing parsers of arbitrary files in JS. they are performant. What can I use as a reference of how to add the step of parser generation in Netron?

Not sure I have a great answer. I'm generally nervous about the approach and the complexity it adds vs. value. 1) why have two different formats instead of just one 2) are new formats really needed by the community vs. migrate to an existing standard 3) XML isn't very popular for ML and hence an odd choice to be supported in tools 4) Is using a parser generator that creates 290k of code really the right approach to parse XML? That said, the `./tools/openvino` could `npm install` the parser generator on the fly and clean up after.

**Comment by demid5111** [comment]
> Running `v10.11.0` and `v11.2.0` on `origin/master` and it works. Which error are you seeing?

@lutzroeder  after I have recreated the fork, everything is ok with node v10.13.0.

**Comment by demid5111** [comment]
> Not sure I have a great answer. I'm generally nervous about the approach and the complexity it adds vs. value. 1) why have two different formats instead of just one 2) are new formats really needed by the community vs. migrate to an existing standard 3) XML isn't very popular for ML and hence an odd choice to be supported in tools 4) Is using a parser generator that creates 290k of code really the right approach to parse XML? That said, the `./tools/openvino` script could call `npm install` to install the parser generator on the fly and delete the `./tools/node_modules` after.

@lutzroeder So, I have made the changes in #194. Please review them

**Comment by demid5111** [comment]
These are files for testing OpenVINO dot files:

[i8_normalized_squeezenet_ssd.dot.zip](https://github.com/lutzroeder/netron/files/2618902/i8_normalized_squeezenet_ssd.dot.zip)
[i8_normalized_squeezenet11.dot.zip](https://github.com/lutzroeder/netron/files/2618904/i8_normalized_squeezenet11.dot.zip)
[i8_normalized_vgg16.dot.zip](https://github.com/lutzroeder/netron/files/2618905/i8_normalized_vgg16.dot.zip)

**Comment by demid5111** [comment]
@lutzroeder Tracking the progress (please reflect it in the issue description - I can not do that directly)
- [x] 1. Opening rm_lstm4f.xml results in TypeError: Cannot read property 'output' of undefined. (#192)
- [x]   2. dot files are not opened any more - need to fix it (#192)
- [x]   3. add preflight check for invalid xml and dot content
- [ ]   4. Add ./tools/openvino script to generate dot and xml reader (#194)
- [ ]   5. Filter attribute defaults to show fewer attributes in the graph
- [ ]   6. Add .dot test files to ./test/models.json (#195)
- [ ]   7. Show weight tensors
- [ ]   8. Graph inputs and outputs should be exposed as Graph.inputs and Graph.outputs
- [ ]   9. Add support for the version 3 of IR (#196)
- [ ]   10. Category color support
- [ ]   11. Add support for the -metadata.json file for better filtering of attributes, operator coloring etc.

For adding to the description:
```md
- [x]   1. Opening rm_lstm4f.xml results in TypeError: Cannot read property 'output' of undefined. (#192)
- [x]   2. dot files are not opened any more - need to fix it (#192)
- [x]   3. add preflight check for invalid xml and dot content
- [ ]   4. Add ./tools/openvino script to generate dot and xml reader (#194)
- [ ]   5. Filter attribute defaults to show fewer attributes in the graph
- [ ]   6. Add .dot test files to ./test/models.json (#195)
- [ ]   7. Show weight tensors
- [ ]   8. Graph inputs and outputs should be exposed as Graph.inputs and Graph.outputs
- [ ]   9. Add support for the version 3 of IR (#196)
- [ ]   10. Category color support
- [ ]   11. Add support for the -metadata.json file for better filtering of attributes, operator coloring etc.
```

**Comment by demid5111** [comment]
@lutzroeder I need your advice. I am now switching to the item !7. How would you recommend to do it taking into consideration that structure of the model (only structure) is in `.xml` file and weights/biases (only binary data) is in `.bin`.  I would be glad to hear your suggestions in order to not loose time with inappropriate solution from the design perspective.

**Comment by demid5111** [comment]
@lutzroeder and also the question about coloring (!10). What can I use as a reference? Is it mandatory to define the `-metadata.json` file?

**Comment by lutzroeder** [comment]
> @lutzroeder I need your advice. I am now switching to the item !7. How would you recommend to do it taking into consideration that structure of the model (only structure) is in `.xml` file and weights/biases (only binary data) is in `.bin`. I would be glad to hear your suggestions in order to not loose time with inappropriate solution from the design perspective.

Have a look at `src/caffe2.js` which uses a similar approach loading a binary tensor file called  `init_net.pb`. Call `context.request` to load the file from the same directory as the model file. Make sure to recover if the file failed to load. For decoding, `src/mxnet.js` might be a good example which has an `ndarray` decoder for a separate `parametersEntry.data` byte array. For test, `models.json` supports comma separated lists for `target` and `source` and picks the first entry as the model file.

**Comment by lutzroeder** [comment]
> @lutzroeder and also the question about coloring (!10). What can I use as a reference? Is it mandatory to define the `-metadata.json` file?

It is not "mandatory", it could be hardcoded in code. However, in practice you will quickly notice the benefits of having the metadata in a separate file. The format is very similar between all the frameworks and should work for yours as well. For most frameworks the color categories are manually added to `-metadata.json` but other information like documentation gets updated via scripts.

**Comment by artyomtugaryov** [comment]
@lutzroeder @demid5111 this is the amazing news that OpenVINO format is supported in Netron.

Please consider adding three more features:
1. back edges support for TensorIterator
2. eltwise operation does not expose the type
3. mark subgraph of TensorIterator somehow for easy distinguishing

**Comment by demid5111** [comment]
@lutzroeder thank you for updating the issue. Could you please add link to the PR for the items in the description so that we could later quickly navigate to it?

For items 10 and 11:
`(#191)`

My next step would be adding the support for weights. Thank you for the answer above, I will use it as a starting point.

**Comment by lutzroeder** [comment]
@demid5111 any updates on these tasks? In particular will 12. and 13. be done by end of Jan? What's the plan for 5.?

**Comment by demid5111** [comment]
@lutzroeder  can you tell more about the point 5? If it is not bery complex, I will do it before points 12 and 13.
I have not yet started working on the re-writing parser. Hopefully, I will start on 29th of January, I will let you know.

**Comment by demid5111** [comment]
@lutzroeder I need to say that your latest commit introduces degradation for the Netron support for the OpenVINO IR v4. I have checked it locally - TensorIterator layer can not be parsed correctly and the whole network can not be rendered at all. Lets revert the commit and I will build upon your version and propose as a pull request till the end of the week. How does that sound for you? Thank you for starting the work with transition to the DOM parser.

**Comment by lutzroeder** [comment]
@demid5111 Can you add the `TensorIterator` support back. It is not used by any test files so adding a test file would be great as well.

**Comment by demid5111** [comment]
@lutzroeder no problem, I will do that. is it possible not to make the new version/release of the product without TensorIterator being fixed?

**Comment by demid5111** [comment]
@lutzroeder yes, I am working on the item 7. however, temporarily switching to the TensorIterator issue

**Comment by demid5111** [comment]
@lutzroeder the fix is on the way. I have made a half of work - it is in my fork's master to the moment. I will make a PR in a day or two with the final version. Thank you for waiting for the fix and not upgrading the release version!

**Comment by demid5111** [comment]
@lutzroeder those are files for testing the fix for the TensorIterator: 

[with_pad_simple.xml.zip](https://github.com/lutzroeder/netron/files/2871673/with_pad_simple.xml.zip)
[with_nd_conv_simple.xml.zip](https://github.com/lutzroeder/netron/files/2871674/with_nd_conv_simple.xml.zip)
[with_gather.xml.zip](https://github.com/lutzroeder/netron/files/2871676/with_gather.xml.zip)
[ti_with_large_body.xml.zip](https://github.com/lutzroeder/netron/files/2871678/ti_with_large_body.xml.zip)

**Comment by lutzroeder** [comment]
@demid5111 any status updates on 7)?

**Comment by demid5111** [comment]
@lutzroeder there are issues with binary convolution weights. I am now exploring it. eta is end of next week.

**Comment by lutzroeder** [comment]
@demid5111 any status updates on 7)?

**Comment by lutzroeder** [comment]
[int4-model.zip](https://github.com/lutzroeder/netron/files/6273773/int4-model.zip)
