### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by lutzroeder** [lutzroeder/netron#627]
Building arm64 binaries:
- [x] electron-userland/electron-builder#5475
- [x] electron-userland/electron-builder#5495

Enabling build tools and scripts: 
- [x] numpy/numpy#18143
- [x] pytorch/pytorch#51854
- [x] scipy/scipy#13409
- [x] scikit-learn/scikit-learn#19137
- [ ] tensorflow/tensorflow#47782

**Comment by ogrisel** [comment]
Note:  scikit-learn/scikit-learn#18861 is about pip refusing to install the macosx_10_9 on Intel Big Sur. It is unrelated to Apple Silicon support (different hardware) unless you plan to rely on Rosetta 2 (the Intel / ARM translation layer of macOS).

We do not yet publish Apple Silicon compatible wheels on pypi.org. However, conda-forge has already native binary packages for Apple Silicon (known as the `osx-arm64` platform for conda-forge): https://github.com/conda-forge/miniforge#download

This includes numpy, scipy and scikit-learn among other things.

**Comment by lutzroeder** [comment]
@ogrisel yes, this is needed at build-time only and running these through Rosetta should be fine for now. After updating pip and nightly bits the scikit-learn scripts are now working.
